typography_spectrum: 0.5220952092204243
color:
  brandStrength: 0.6149683492258191
  lightness: 0.8673350524622947
  saturation: 0.03585024154745042
  rhythmicContrast: 0.48602852784097195
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.4232201499398798
author:
  name: Epic Nooblet
  email: epicnoobletgames@gmail.com
  url: ''
name: Epic Nooblet
navigation:
  - name: Giving up WordPress...maybe?
    id: 0c76fd85-514b-4d70-b5cb-32964b0a7a14
    type: content
  - name: 'World of Warcraft: Broken Shore Scenario'
    id: 11c14316-23b3-445a-9ce9-7e3379f6df7e
    type: content
title: Nooblet's Random Thoughts
